__include__: [
  './dfine_hgnetv2_s_bdd100k.yml',
  '../base/deim.yml'
]

print_freq: 2500
checkpoint_freq: 20
output_dir: deim_dfine_bdd100k/s/baseline_se

HGNetv2:
  agg: se

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*bn).*$'
      lr: 0.0002
    - 
      params: '^(?=.*(?:norm|bn)).*$'     # except bias
      weight_decay: 0.

  lr: 0.0004
  betas: [0.9, 0.999]
  weight_decay: 0.0001


# Increase to search for the optimal ema
epoches: 132 # 120 + 4n

## Our LR-Scheduler
flat_epoch: 64    # 4 + epoch // 2, e.g., 40 = 4 + 72 / 2
no_aug_epoch: 12

## Our DataAug
train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: [4, 64, 120]   # list 
  total_batch_size: 16
  num_workers: 8

  collate_fn:
    mixup_epochs: [4, 64]
    stop_epoch: 120

val_dataloader:
  total_batch_size: 1
  num_workers: 8